LineLength:
  Enabled: false

MethodLength:
  Max: 30

Documentation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - lib/public/**/*
    - build/**/*
