LineLength:
  Enabled: false

MethodLength:
  Max: 30

Documentation:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - lib/public/**/*
    - build/**/*
