sudo: false
cache: bundler
language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
  fast_finish: true
before_install: gem update --remote bundler
install:
  - bundle install --retry=3
rvm:
  - 2.2.2
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
script:
  - bundle exec rspec
  - bundle exec rubocop
